# action.yml
name: "Fuzz"
description: "Fuzz a Test Collection until it crashes or reaches the timeout"
inputs:
  cognito_user:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: true
  cognito_password:
    description: "Cognito credentials to authenticate with Code-Intelligence's fuzzing server"
    required: true
  project:
    description: "Name of the project"
    required: true
  test_collection:
    description: "Name of the Test Collection in the specified project"
    required: true
  report_email:
    description: "E-mail to receive crash reports"
    required: false
  timeout:
    description: "Timeout (in seconds) to monitor the fuzzing. If no crash was found when it times out, the action is considered successful."
    required: false
    default: 300
  fuzzing_server_address:
    description: "URL of Code-Intelligence's gRPC server for fuzzing"
    required: false
    default: "grpc-api.cloud.code-intelligence.com:443"
runs:
  using: "docker"
  image: "docker://cifuzz/cictl"
  pre-entrypoint: 'sh -c ls && which cictl && cictl login -u "${INPUT_COGNITO_USER}" -p "${INPUT_COGNITO_PASSWORD}"'
  entrypoint: 'cictl start_and_monitor_fuzzing --duration="${INPUT_TIMEOUT}" --daemon_listen_address="${FUZZER_DAEMON_ADDRESS}" --project_name="${PROJECT_NAME}" --campaign_name="fuzz_api_DoStuff" --cloud_report_recipient_email="${REPORT_EMAIL}"'
